<?php

namespace Database\Seeders;

use App\Models\NotificationTemplate;
use Illuminate\Database\Seeder;

class NotificationTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            // === GENEL ===
            [
                'key' => 'welcome',
                'category' => 'genel',
                'title' => 'Hoşgeldiniz (Yeni Hesap)',
                'sms_content' => 'Merhaba {{ad}}, Proxynetic\'e hoş geldiniz! Hesabınız başarıyla oluşturuldu.',
                'mail_subject' => 'Proxynetic\'e Hoş Geldiniz!',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#2563eb;">Hoş Geldiniz, {{ad}} {{soyad}}!</h2><p>Proxynetic ailesine katıldığınız için teşekkür ederiz.</p><p>Hesabınız başarıyla oluşturulmuştur. Hemen giriş yaparak hizmetlerimizden yararlanmaya başlayabilirsiniz.</p><p><a href="{{site_url}}" style="display:inline-block;padding:12px 24px;background:#2563eb;color:#fff;text-decoration:none;border-radius:6px;">Panele Git</a></p><p style="color:#888;font-size:12px;">Bu e-posta {{site_adi}} tarafından gönderilmiştir.</p></div>',
                'variables' => ['ad', 'soyad', 'email', 'site_url', 'site_adi'],
                'sort_order' => 1,
            ],

            // === FATURA ===
            [
                'key' => 'invoice_created',
                'category' => 'fatura',
                'title' => 'Fatura Oluşturuldu',
                'sms_content' => '{{ad}} {{soyad}}, {{fatura_no}} numaralı faturanız oluşturulmuştur. Tutar: {{tutar}} TL. Son ödeme: {{son_odeme_tarihi}}',
                'mail_subject' => 'Fatura Oluşturuldu - #{{fatura_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#16a34a;">Faturanız Oluşturuldu</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{fatura_no}}</strong> numaralı faturanız oluşturulmuştur.</p><table style="width:100%;border-collapse:collapse;margin:15px 0;"><tr><td style="padding:8px;border:1px solid #ddd;font-weight:bold;">Fatura No</td><td style="padding:8px;border:1px solid #ddd;">#{{fatura_no}}</td></tr><tr><td style="padding:8px;border:1px solid #ddd;font-weight:bold;">Tutar</td><td style="padding:8px;border:1px solid #ddd;">{{tutar}} TL</td></tr><tr><td style="padding:8px;border:1px solid #ddd;font-weight:bold;">Son Ödeme Tarihi</td><td style="padding:8px;border:1px solid #ddd;">{{son_odeme_tarihi}}</td></tr></table><p><a href="{{fatura_url}}" style="display:inline-block;padding:12px 24px;background:#16a34a;color:#fff;text-decoration:none;border-radius:6px;">Faturayı Görüntüle</a></p></div>',
                'variables' => ['ad', 'soyad', 'fatura_no', 'tutar', 'son_odeme_tarihi', 'fatura_url'],
                'sort_order' => 10,
            ],
            [
                'key' => 'invoice_refunded',
                'category' => 'fatura',
                'title' => 'Fatura İade Edildi',
                'sms_content' => '{{ad}} {{soyad}}, {{fatura_no}} numaralı faturanız iade edilmiştir. İade tutarı: {{tutar}} TL',
                'mail_subject' => 'Fatura İade Edildi - #{{fatura_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#f59e0b;">Fatura İade Edildi</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{fatura_no}}</strong> numaralı faturanız iade edilmiştir.</p><p><strong>İade Tutarı:</strong> {{tutar}} TL</p></div>',
                'variables' => ['ad', 'soyad', 'fatura_no', 'tutar'],
                'sort_order' => 11,
            ],
            [
                'key' => 'invoice_cancelled',
                'category' => 'fatura',
                'title' => 'Fatura İptal Edildi',
                'sms_content' => '{{ad}} {{soyad}}, {{fatura_no}} numaralı faturanız iptal edilmiştir.',
                'mail_subject' => 'Fatura İptal Edildi - #{{fatura_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#ef4444;">Fatura İptal Edildi</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{fatura_no}}</strong> numaralı faturanız iptal edilmiştir.</p><p>Herhangi bir sorunuz varsa destek ekibimizle iletişime geçebilirsiniz.</p></div>',
                'variables' => ['ad', 'soyad', 'fatura_no', 'tutar'],
                'sort_order' => 12,
            ],
            [
                'key' => 'invoice_reminder',
                'category' => 'fatura',
                'title' => 'Fatura Hatırlatma',
                'sms_content' => '{{ad}} {{soyad}}, {{fatura_no}} numaralı faturanızın son ödeme tarihi {{son_odeme_tarihi}}. Tutar: {{tutar}} TL',
                'mail_subject' => 'Fatura Ödeme Hatırlatması - #{{fatura_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#f59e0b;">Fatura Ödeme Hatırlatması</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{fatura_no}}</strong> numaralı faturanızın son ödeme tarihi yaklaşmaktadır.</p><table style="width:100%;border-collapse:collapse;margin:15px 0;"><tr><td style="padding:8px;border:1px solid #ddd;font-weight:bold;">Tutar</td><td style="padding:8px;border:1px solid #ddd;">{{tutar}} TL</td></tr><tr><td style="padding:8px;border:1px solid #ddd;font-weight:bold;">Son Ödeme</td><td style="padding:8px;border:1px solid #ddd;">{{son_odeme_tarihi}}</td></tr></table><p><a href="{{fatura_url}}" style="display:inline-block;padding:12px 24px;background:#f59e0b;color:#fff;text-decoration:none;border-radius:6px;">Ödeme Yap</a></p></div>',
                'variables' => ['ad', 'soyad', 'fatura_no', 'tutar', 'son_odeme_tarihi', 'fatura_url'],
                'sort_order' => 13,
            ],
            [
                'key' => 'invoice_overdue',
                'category' => 'fatura',
                'title' => 'Fatura Gecikme Bildirimi',
                'sms_content' => '{{ad}} {{soyad}}, {{fatura_no}} numaralı faturanızın son ödeme tarihi geçmiştir. Lütfen en kısa sürede ödeme yapınız.',
                'mail_subject' => 'Fatura Gecikmesi - #{{fatura_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#ef4444;">Fatura Ödeme Gecikmesi</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{fatura_no}}</strong> numaralı faturanızın son ödeme tarihi geçmiştir. Hizmetinizin kesintiye uğramaması için lütfen en kısa sürede ödeme yapınız.</p><p><strong>Tutar:</strong> {{tutar}} TL</p><p><a href="{{fatura_url}}" style="display:inline-block;padding:12px 24px;background:#ef4444;color:#fff;text-decoration:none;border-radius:6px;">Hemen Öde</a></p></div>',
                'variables' => ['ad', 'soyad', 'fatura_no', 'tutar', 'son_odeme_tarihi', 'fatura_url'],
                'sort_order' => 14,
            ],
            [
                'key' => 'invoice_paid',
                'category' => 'fatura',
                'title' => 'Fatura Ödemesi Onaylandı',
                'sms_content' => '{{ad}} {{soyad}}, {{fatura_no}} numaralı faturanızın ödemesi onaylanmıştır. Teşekkür ederiz.',
                'mail_subject' => 'Ödeme Onaylandı - #{{fatura_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#16a34a;">Ödeme Onaylandı</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{fatura_no}}</strong> numaralı faturanızın ödemesi başarıyla alınmıştır.</p><p><strong>Ödenen Tutar:</strong> {{tutar}} TL</p><p>Teşekkür ederiz.</p></div>',
                'variables' => ['ad', 'soyad', 'fatura_no', 'tutar'],
                'sort_order' => 15,
            ],
            [
                'key' => 'invoice_formalized',
                'category' => 'fatura',
                'title' => 'Resmi Fatura Hazırlandı',
                'sms_content' => '{{ad}} {{soyad}}, {{fatura_no}} numaralı resmi faturanız hazırlanmıştır.',
                'mail_subject' => 'Resmi Fatura Hazır - #{{fatura_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#2563eb;">Resmi Faturanız Hazır</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{fatura_no}}</strong> numaralı resmi faturanız hazırlanmıştır. Faturanızı panelden görüntüleyip indirebilirsiniz.</p><p><a href="{{fatura_url}}" style="display:inline-block;padding:12px 24px;background:#2563eb;color:#fff;text-decoration:none;border-radius:6px;">Faturayı İndir</a></p></div>',
                'variables' => ['ad', 'soyad', 'fatura_no', 'fatura_url'],
                'sort_order' => 16,
            ],
            [
                'key' => 'invoice_pending_approval',
                'category' => 'fatura',
                'title' => 'Fatura Ödeme Onayı Bekliyor',
                'sms_content' => '{{ad}} {{soyad}}, {{fatura_no}} numaralı faturanız için ödeme onayı beklenmektedir.',
                'mail_subject' => 'Ödeme Onayı Bekliyor - #{{fatura_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#f59e0b;">Ödeme Onayı Bekliyor</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{fatura_no}}</strong> numaralı faturanız için yaptığınız ödeme incelenmektedir. En kısa sürede onaylanacaktır.</p><p><strong>Tutar:</strong> {{tutar}} TL</p></div>',
                'variables' => ['ad', 'soyad', 'fatura_no', 'tutar'],
                'sort_order' => 17,
            ],
            [
                'key' => 'invoice_auto_payment_failed',
                'category' => 'fatura',
                'title' => 'Otomatik Fatura Ödemesi Başarısız',
                'sms_content' => '{{ad}} {{soyad}}, {{fatura_no}} numaralı faturanızın otomatik ödemesi başarısız olmuştur. Lütfen manuel ödeme yapınız.',
                'mail_subject' => 'Otomatik Ödeme Başarısız - #{{fatura_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#ef4444;">Otomatik Ödeme Başarısız</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{fatura_no}}</strong> numaralı faturanızın otomatik ödemesi gerçekleştirilemedi. Hizmetinizin kesintiye uğramaması için lütfen manuel ödeme yapınız.</p><p><strong>Tutar:</strong> {{tutar}} TL</p><p><a href="{{fatura_url}}" style="display:inline-block;padding:12px 24px;background:#ef4444;color:#fff;text-decoration:none;border-radius:6px;">Manuel Ödeme Yap</a></p></div>',
                'variables' => ['ad', 'soyad', 'fatura_no', 'tutar', 'fatura_url'],
                'sort_order' => 18,
            ],
            [
                'key' => 'subscription_payment_failed',
                'category' => 'fatura',
                'title' => 'Abonelik Ödemesi Başarısız',
                'sms_content' => '{{ad}} {{soyad}}, abonelik ödemeniz başarısız olmuştur. Hizmetiniz askıya alınabilir.',
                'mail_subject' => 'Abonelik Ödemesi Başarısız',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#ef4444;">Abonelik Ödemesi Başarısız</h2><p>Sayın {{ad}} {{soyad}},</p><p>Abonelik ödemeniz gerçekleştirilemedi. Hizmetinizin kesintiye uğramaması için lütfen ödeme bilgilerinizi güncelleyiniz.</p><p><a href="{{site_url}}" style="display:inline-block;padding:12px 24px;background:#ef4444;color:#fff;text-decoration:none;border-radius:6px;">Panele Git</a></p></div>',
                'variables' => ['ad', 'soyad', 'site_url'],
                'sort_order' => 19,
            ],

            // === SİPARİŞ ===
            [
                'key' => 'order_received',
                'category' => 'siparis',
                'title' => 'Sipariş Alındı',
                'sms_content' => '{{ad}} {{soyad}}, #{{siparis_no}} numaralı siparişiniz alınmıştır. Ürün: {{urun_adi}}',
                'mail_subject' => 'Siparişiniz Alındı - #{{siparis_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#2563eb;">Siparişiniz Alındı</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{siparis_no}}</strong> numaralı siparişiniz başarıyla alınmıştır.</p><table style="width:100%;border-collapse:collapse;margin:15px 0;"><tr><td style="padding:8px;border:1px solid #ddd;font-weight:bold;">Ürün</td><td style="padding:8px;border:1px solid #ddd;">{{urun_adi}}</td></tr><tr><td style="padding:8px;border:1px solid #ddd;font-weight:bold;">Sipariş No</td><td style="padding:8px;border:1px solid #ddd;">#{{siparis_no}}</td></tr></table><p>Siparişiniz en kısa sürede işleme alınacaktır.</p></div>',
                'variables' => ['ad', 'soyad', 'siparis_no', 'urun_adi'],
                'sort_order' => 20,
            ],
            [
                'key' => 'order_confirmed',
                'category' => 'siparis',
                'title' => 'Sipariş Onaylandı',
                'sms_content' => '{{ad}} {{soyad}}, #{{siparis_no}} numaralı siparişiniz onaylanmıştır.',
                'mail_subject' => 'Sipariş Onaylandı - #{{siparis_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#16a34a;">Siparişiniz Onaylandı</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{siparis_no}}</strong> numaralı siparişiniz onaylanmış ve aktif edilmiştir.</p><p><strong>Ürün:</strong> {{urun_adi}}</p><p><a href="{{siparis_url}}" style="display:inline-block;padding:12px 24px;background:#16a34a;color:#fff;text-decoration:none;border-radius:6px;">Siparişi Görüntüle</a></p></div>',
                'variables' => ['ad', 'soyad', 'siparis_no', 'urun_adi', 'siparis_url'],
                'sort_order' => 21,
            ],
            [
                'key' => 'order_suspended',
                'category' => 'siparis',
                'title' => 'Sipariş Askıya Alındı',
                'sms_content' => '{{ad}} {{soyad}}, #{{siparis_no}} numaralı siparişiniz askıya alınmıştır.',
                'mail_subject' => 'Sipariş Askıya Alındı - #{{siparis_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#f59e0b;">Sipariş Askıya Alındı</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{siparis_no}}</strong> numaralı siparişiniz askıya alınmıştır. Detaylı bilgi için destek ekibimizle iletişime geçebilirsiniz.</p></div>',
                'variables' => ['ad', 'soyad', 'siparis_no', 'urun_adi'],
                'sort_order' => 22,
            ],
            [
                'key' => 'order_activated',
                'category' => 'siparis',
                'title' => 'Sipariş Aktif Edildi',
                'sms_content' => '{{ad}} {{soyad}}, #{{siparis_no}} numaralı siparişiniz tekrar aktif edilmiştir.',
                'mail_subject' => 'Sipariş Aktif Edildi - #{{siparis_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#16a34a;">Sipariş Aktif Edildi</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{siparis_no}}</strong> numaralı siparişiniz tekrar aktif edilmiştir. Hizmetiniz kullanıma hazırdır.</p><p><a href="{{siparis_url}}" style="display:inline-block;padding:12px 24px;background:#16a34a;color:#fff;text-decoration:none;border-radius:6px;">Siparişi Görüntüle</a></p></div>',
                'variables' => ['ad', 'soyad', 'siparis_no', 'urun_adi', 'siparis_url'],
                'sort_order' => 23,
            ],
            [
                'key' => 'order_cancelled',
                'category' => 'siparis',
                'title' => 'Sipariş İptal Edildi',
                'sms_content' => '{{ad}} {{soyad}}, #{{siparis_no}} numaralı siparişiniz iptal edilmiştir.',
                'mail_subject' => 'Sipariş İptal Edildi - #{{siparis_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#ef4444;">Sipariş İptal Edildi</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{siparis_no}}</strong> numaralı siparişiniz iptal edilmiştir.</p><p>Herhangi bir sorunuz varsa destek ekibimizle iletişime geçebilirsiniz.</p></div>',
                'variables' => ['ad', 'soyad', 'siparis_no', 'urun_adi'],
                'sort_order' => 24,
            ],
            [
                'key' => 'order_renewed',
                'category' => 'siparis',
                'title' => 'Ürün/Hizmet Süresi Uzatıldı',
                'sms_content' => '{{ad}} {{soyad}}, {{urun_adi}} hizmetinizin süresi {{yeni_bitis_tarihi}} tarihine kadar uzatılmıştır.',
                'mail_subject' => 'Hizmet Süreniz Uzatıldı',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#16a34a;">Hizmet Süreniz Uzatıldı</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>{{urun_adi}}</strong> hizmetinizin süresi başarıyla uzatılmıştır.</p><p><strong>Yeni Bitiş Tarihi:</strong> {{yeni_bitis_tarihi}}</p><p>Hizmetiniz kesintisiz devam etmektedir.</p></div>',
                'variables' => ['ad', 'soyad', 'urun_adi', 'siparis_no', 'yeni_bitis_tarihi'],
                'sort_order' => 25,
            ],

            // === DESTEK ===
            [
                'key' => 'support_auto_resolved',
                'category' => 'destek',
                'title' => 'Destek Talebi Çözümlendi (Otomatik)',
                'sms_content' => '{{ad}} {{soyad}}, #{{talep_no}} numaralı destek talebiniz otomatik olarak çözümlenmiştir.',
                'mail_subject' => 'Destek Talebi Çözümlendi - #{{talep_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#16a34a;">Destek Talebi Çözümlendi</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{talep_no}}</strong> numaralı destek talebiniz otomatik olarak çözümlenmiştir.</p><p><strong>Konu:</strong> {{konu}}</p><p>Eğer sorununuz devam ediyorsa yeni bir destek talebi oluşturabilirsiniz.</p></div>',
                'variables' => ['ad', 'soyad', 'talep_no', 'konu'],
                'sort_order' => 30,
            ],
            [
                'key' => 'support_replied',
                'category' => 'destek',
                'title' => 'Destek Talebi Yanıtlandı',
                'sms_content' => '{{ad}} {{soyad}}, #{{talep_no}} numaralı destek talebiniz yanıtlanmıştır.',
                'mail_subject' => 'Destek Talebinize Yanıt Geldi - #{{talep_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#2563eb;">Destek Talebinize Yanıt Geldi</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{talep_no}}</strong> numaralı destek talebinize yanıt gelmiştir.</p><p><strong>Konu:</strong> {{konu}}</p><p><a href="{{talep_url}}" style="display:inline-block;padding:12px 24px;background:#2563eb;color:#fff;text-decoration:none;border-radius:6px;">Yanıtı Görüntüle</a></p></div>',
                'variables' => ['ad', 'soyad', 'talep_no', 'konu', 'talep_url'],
                'sort_order' => 31,
            ],
            [
                'key' => 'admin_notification',
                'category' => 'destek',
                'title' => 'Yönetici Bildirim Oluşturdu',
                'sms_content' => '{{ad}} {{soyad}}, yeni bir yönetici bildirimi var: {{bildirim_baslik}}',
                'mail_subject' => 'Yeni Bildirim: {{bildirim_baslik}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#7c3aed;">Yeni Bildirim</h2><p>Sayın {{ad}} {{soyad}},</p><p>Yönetici tarafından yeni bir bildirim oluşturulmuştur:</p><div style="background:#f3f4f6;padding:15px;border-radius:8px;margin:15px 0;"><strong>{{bildirim_baslik}}</strong><p>{{bildirim_icerik}}</p></div></div>',
                'variables' => ['ad', 'soyad', 'bildirim_baslik', 'bildirim_icerik'],
                'sort_order' => 32,
            ],
            [
                'key' => 'support_created',
                'category' => 'destek',
                'title' => 'Destek Talebiniz Oluşturulmuştur',
                'sms_content' => '{{ad}} {{soyad}}, #{{talep_no}} numaralı destek talebiniz oluşturulmuştur. Konu: {{konu}}',
                'mail_subject' => 'Destek Talebiniz Oluşturuldu - #{{talep_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#2563eb;">Destek Talebiniz Oluşturuldu</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{talep_no}}</strong> numaralı destek talebiniz başarıyla oluşturulmuştur.</p><p><strong>Konu:</strong> {{konu}}</p><p>Ekibimiz en kısa sürede talebinizi inceleyecektir.</p><p><a href="{{talep_url}}" style="display:inline-block;padding:12px 24px;background:#2563eb;color:#fff;text-decoration:none;border-radius:6px;">Talebi Görüntüle</a></p></div>',
                'variables' => ['ad', 'soyad', 'talep_no', 'konu', 'talep_url'],
                'sort_order' => 33,
            ],
            [
                'key' => 'support_in_progress',
                'category' => 'destek',
                'title' => 'Destek Talebi İşleme Alındı',
                'sms_content' => '{{ad}} {{soyad}}, #{{talep_no}} numaralı destek talebiniz işleme alınmıştır.',
                'mail_subject' => 'Destek Talebi İşleme Alındı - #{{talep_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#f59e0b;">Destek Talebi İşleme Alındı</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{talep_no}}</strong> numaralı destek talebiniz ekibimiz tarafından işleme alınmıştır.</p><p><strong>Konu:</strong> {{konu}}</p><p>En kısa sürede yanıtlanacaktır.</p></div>',
                'variables' => ['ad', 'soyad', 'talep_no', 'konu'],
                'sort_order' => 34,
            ],
            [
                'key' => 'support_resolved',
                'category' => 'destek',
                'title' => 'Destek Talebi Çözümlendi',
                'sms_content' => '{{ad}} {{soyad}}, #{{talep_no}} numaralı destek talebiniz çözümlenmiştir.',
                'mail_subject' => 'Destek Talebi Çözümlendi - #{{talep_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#16a34a;">Destek Talebi Çözümlendi</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{talep_no}}</strong> numaralı destek talebiniz çözümlenmiştir.</p><p><strong>Konu:</strong> {{konu}}</p><p>Eğer sorununuz devam ediyorsa talebi yeniden açabilirsiniz.</p><p><a href="{{talep_url}}" style="display:inline-block;padding:12px 24px;background:#16a34a;color:#fff;text-decoration:none;border-radius:6px;">Talebi Görüntüle</a></p></div>',
                'variables' => ['ad', 'soyad', 'talep_no', 'konu', 'talep_url'],
                'sort_order' => 35,
            ],
            [
                'key' => 'support_replied_email_piping',
                'category' => 'destek',
                'title' => 'Destek Talebi Yanıtlandı (E-Mail Piping)',
                'sms_content' => '{{ad}} {{soyad}}, #{{talep_no}} numaralı destek talebinize e-posta üzerinden yanıt gelmiştir.',
                'mail_subject' => 'Destek Talebi Yanıtlandı - #{{talep_no}}',
                'mail_content' => '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><h2 style="color:#2563eb;">Destek Talebinize Yanıt Geldi</h2><p>Sayın {{ad}} {{soyad}},</p><p><strong>#{{talep_no}}</strong> numaralı destek talebinize e-posta üzerinden yanıt gelmiştir.</p><p><strong>Konu:</strong> {{konu}}</p><p><a href="{{talep_url}}" style="display:inline-block;padding:12px 24px;background:#2563eb;color:#fff;text-decoration:none;border-radius:6px;">Yanıtı Görüntüle</a></p></div>',
                'variables' => ['ad', 'soyad', 'talep_no', 'konu', 'talep_url'],
                'sort_order' => 36,
            ],
        ];

        foreach ($templates as $template) {
            NotificationTemplate::updateOrCreate(
                ['key' => $template['key']],
                $template
            );
        }
    }
}
